server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: user-service.log

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:55432/microservice_hotel
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

#  datasource:
#    url: jdbc:h2:file:./data/microservice_hotel
#    driver-class-name: org.h2.Driver
#    username: h2
#    password: h2
#  h2:
#    console:
#      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    drop-first: true
    url: jdbc:postgresql://localhost:55432/microservice_hotel
    default-schema: public

#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    user: h2
#    password: h2
#    drop-first: true
#    url: jdbc:h2:file:./data/microservice_hotel
#    default-schema: public
