-- ORACLE
-- @see liquibase: drop-first: true
-- microservice_hotel.hotel definition
-- Drop table
-- BEGIN
-- EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS MICROSERVICE_HOTEL.hotel';
-- EXCEPTION
--    WHEN OTHERS THEN
--       IF SQLCODE != -942 THEN
--          RAISE;
-- END IF;
-- END/

CREATE TABLE MICROSERVICE_HOTEL.hotel
(
    id number(38,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WiTH 1000,
    about varchar(100) NULL,
    location varchar(255) NULL,
    name  varchar(20) NULL,
    CONSTRAINT msh_hotel_pkey PRIMARY KEY (id)
)
/
