databaseChangeLog:
  - changeSet:
      id: create-document-rating
      author: alejovic@gmail.com
      labels: example-label
      context: example-context
      comment: example-comment

      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: ratings_pkey
                  name: id
                  type: varchar(50)
              - column:
                  constraints:
                    nullable: false
                  name: userId
                  type: int
              - column:
                  constraints:
                    nullable: false
                  name: hotelId
                  type: int
              - column:
                  constraints:
                    nullable: false
                  name: rating
                  type: int
              - column:
                  name: feedback
                  type: varchar(100)
            tableName: user_ratings
