server:
  port: 8083

logging:
  file:
    name: hotel-rating.log

spring:
  data:
    mongodb:
      uri: mongodb://localhost:57017/microservice_hotel
      username: microservice_hotel
      password: password

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: microservice_hotel
    password: password
    drop-first: true
    url: mongodb://localhost:57017/microservice_hotel
    default-schema: public

